/** Family-safe blocklist — whole-word and severe-pattern matching. */
export const PROFANITY_WORDS = new Set(
  [
    "anal",
    "anus",
    "arse",
    "ass",
    "asshole",
    "bastard",
    "bitch",
    "blowjob",
    "bollocks",
    "boner",
    "boob",
    "boobs",
    "bullshit",
    "bung",
    "butt",
    "butthole",
    "clit",
    "cock",
    "coon",
    "crap",
    "cum",
    "cunt",
    "damn",
    "dick",
    "dildo",
    "douche",
    "dyke",
    "fag",
    "faggot",
    "fuck",
    "fucker",
    "fucking",
    "goddamn",
    "hell",
    "homo",
    "hooker",
    "horny",
    "jerkoff",
    "jizz",
    "kike",
    "kys",
    "milf",
    "motherfucker",
    "nazi",
    "negro",
    "nigga",
    "nigger",
    "nipple",
    "nude",
    "nudes",
    "orgasm",
    "penis",
    "piss",
    "porn",
    "porno",
    "pussy",
    "queer",
    "rape",
    "rapist",
    "retard",
    "retarded",
    "scrotum",
    "sex",
    "sexy",
    "shit",
    "shitty",
    "slut",
    "spic",
    "suck",
    "tits",
    "titty",
    "twat",
    "vagina",
    "vibrator",
    "wank",
    "wanker",
    "whore",
    "wtf",
  ].map((w) => w.toLowerCase()),
);

/** Phrases blocked anywhere in text (lowercase). */
export const BLOCKED_PHRASES = [
  "kill yourself",
  "kys",
  "send nudes",
  "child porn",
  "cp ",
  " hitler ",
  "heil hitler",
  "white power",
  "sieg heil",
];

/** Image / GIF hosts and patterns blocked in message text. */
export const BLOCKED_URL_PATTERNS = [
  /giphy\.com/i,
  /tenor\.com/i,
  /media\.tenor\.com/i,
  /gfycat\.com/i,
  /redgifs\.com/i,
  /\.gif(?:\?|$|#)/i,
  /discordapp\.com\/attachments\/.*\.gif/i,
];
